<?php echo $header; ?>
<!-- Main Content -->
<main>
	<!-- Agreement -->
	<div class="panel agreement">
	</div>
	<!-- Description -->
	<div class="panel description">
	</div>
	<!-- Game -->
	<div class="panel game">
	</div>
	<!-- Success -->
	<div class="panel success">
	</div>
	<!-- Fail -->
	<div class="panel fail fail-template">

	</div>
	<!-- Played -->
	<div class="panel played">
	</div>
	<!-- The End -->
	</div>
	<!-- Winners -->
	<div class="panel winners">
	</div>
</main>
<?php echo $footer; ?>